services:
  archisteamfarm:
    image: justarchi/archisteamfarm
    environment:
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
    ports:
      - 1242:1242
    volumes:
      - ./config:/app/config
      - ./plugins:/app/plugins
