version: "3"
services:
  napcat:
    environment:
      - ACCOUNT=${QQ_NUMBER}
      - WS_ENABLE=true
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}

    ports:
      - "3001:3001"
      - "6099:6099"
    container_name: napcat
    network_mode: bridge
    restart: always
    image: mlikiowa/napcat-docker:latest
    volumes:
      - ./napcat-config:/usr/src/app/napcat/config
      - ./qq-data:/root/.config/QQ
