services:
  db2:
    image: icr.io/db2_community/db2
    stdin_open: true
    tty: true
    container_name: db2
    privileged: true
    ports:
      - 50000:50000
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=password
      - DBNAME=db_name
    volumes:
      - ./db2-data:/database
