services:
  sqlserver2019:
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "p@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ./sqlserver-data:/var/opt/mssql
